### ISSUE TITLE
Fix null pointer on url media set

### ISSUE THREAD

**Issue by ajchili** [ajchili/sync#69]
```
java.lang.NullPointerException
	at com.kirinpatel.sync.net.Media.prepareMedia(Media.java:99)
	at com.kirinpatel.sync.gui.VLCJMediaPlayer.setMedia(VLCJMediaPlayer.java:187)
	at com.kirinpatel.sync.net.Client$ClientThread.run(Client.java:84)
	at java.lang.Thread.run(Thread.java:748)
```

This occurred while trying to use [this](https://www.youtube.com/watch?v=7FBwGYCxCRU) url as the media.

**Comment by ajchili** [comment]
After testing local media, it does not work either. It provides the same error.
```
java.lang.NullPointerException
	at com.kirinpatel.sync.net.Media.prepareMedia(Media.java:99)
	at com.kirinpatel.sync.gui.VLCJMediaPlayer.setMedia(VLCJMediaPlayer.java:187)
	at com.kirinpatel.sync.net.Client$ClientThread.run(Client.java:84)
	at java.lang.Thread.run(Thread.java:748)
```
